# Ruff configuration for personal-llm project
# https://docs.astral.sh/ruff/configuration/

# Target Python 3.13
target-version = 'py313'

# Set line length to 88 (Black default)
line-length = 88

# Exclude common directories
exclude = [
    '.git',
    '.venv',
    'venv',
    '__pycache__',
    '.pytest_cache',
    '.ruff_cache',
    'build',
    'dist',
    '*.egg-info',
]

[lint]
# Enable comprehensive rule sets for best practices
select = [
    'F',     # Pyflakes - detect various errors
    'E',     # pycodestyle errors
    'W',     # pycodestyle warnings
    'I',     # isort - import sorting
    'N',     # pep8-naming - naming conventions
    'UP',    # pyupgrade - upgrade syntax for newer Python
    'B',     # flake8-bugbear - find likely bugs
    'C4',    # flake8-comprehensions - better list/dict comprehensions
    'SIM',   # flake8-simplify - simplify code
    'PTH',   # flake8-use-pathlib - prefer pathlib over os.path
    'RUF',   # Ruff-specific rules
]

# Ignore specific rules
ignore = [
    'E501',  # Line too long (handled by formatter)
]

# Allow autofix for all enabled rules
fixable = ['ALL']
unfixable = []

# Allow unused variables when prefixed with underscore
dummy-variable-rgx = '^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$'

[lint.per-file-ignores]
# Allow unused imports in __init__.py files
'__init__.py' = ['F401']
# Relax rules for test files
'test_*.py' = ['S101']  # Allow assert statements in tests

[lint.isort]
# Configure import sorting
known-first-party = ['tokenizer', 'data_loader']
force-single-line = false
lines-after-imports = 2

[format]
# Use single quotes for string formatting (as specified)
quote-style = 'single'

# Use spaces around equal signs in keyword arguments
skip-magic-trailing-comma = false

# Format docstrings
docstring-code-format = true
docstring-code-line-length = 88
